export { AppearanceSettings } from './AppearanceSettings'
export { DangerZoneSettings } from './DangerZoneSettings'
export { DataTransferSettings } from './DataTransferSettings'
export { LanguageSettings } from './LanguageSettings'
export { PlatformDataSettings } from './PlatformDataSettings'
export { PrivacyNotice } from './PrivacyNotice'
export { WidgetSettings } from './WidgetSettings'
