export { AppearanceSettings } from './AppearanceSettings'
export { DataTransferSettings } from './DataTransferSettings'
export { KeyboardShortcutsSettings } from './KeyboardShortcutsSettings'
export { LanguageSettings } from './LanguageSettings'
export { PlatformDataSettings } from './PlatformDataSettings'
export { WidgetSettings } from './WidgetSettings'
